# Generated by Django 3.2.5 on 2021-07-06 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsrecipients'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewsRecipients',
            new_name='NewsLetterRecipients',
        ),
    ]
